### Step 1- Import Libraries

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [19]:
import warnings
warnings.filterwarnings('ignore')

### Step 2-Load the Dataset

In [20]:
data=pd.read_excel("marketing_campaign.xlsx")

### Step 3-See the first Rows

In [21]:
data.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,...,5,0,0,0,0,0,0,3,11,0

head() is used to inspect the first few records and verify that the dataset was loaded correctly and to understand the initial structure of the data.

### Step 4- See the last rows

In [22]:
data.tail()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
2235,10870,1967,Graduation,Married,61223.0,0,1,2013-06-13,46,709,...,5,0,0,0,0,0,0,3,11,0
2236,4001,1946,PhD,Together,64014.0,2,1,2014-06-10,56,406,...,7,0,0,0,1,0,0,3,11,0
2237,7270,1981,Graduation,Divorced,56981.0,0,0,2014-01-25,91,908,...,6,0,1,0,0,0,0,3,11,0
2238,8235,1956,Master,Together,69245.0,0,1,2014-01-24,8,428,...,3,0,0,0,0,0,0,3,11,0
2239,9405,1954,PhD,Married,52869.0,1,1,2012-10-15,40,84,...,7,0,0,0,0,0,0,3,11,1

Mostly to verify that the complete dataset has loaded properly.

### Step 5-Check Dataset Size

In [23]:
data.shape

(2240, 29)

### Step 6- See all columns Names

In [24]:
data.columns

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome',
       'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits',
       'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response'],
      dtype='object')

### Step 7-Understand the Dataset structure

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   datetime64[ns]
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(25), object(2)
memory usage: 507.6+ KB

### Step 8- Statistical Summary

In [26]:
data.describe()

,ID,Year_Birth,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,MntMeatProducts,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
count,2240.000000,2240.000000,2216.000000,2240.000000,2240.000000,2240,2240.000000,2240.000000,2240.000000,2240.000000,...,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.0,2240.0,2240.000000
mean,5592.159821,1968.805804,52247.251354,0.444196,0.506250,2013-07-10 10:01:42.857142784,49.109375,303.935714,26.302232,166.950000,...,5.316518,0.072768,0.074554,0.072768,0.064286,0.013393,0.009375,3.0,11.0,0.149107
min,0.000000,1893.000000,1730.000000,0.000000,0.000000,2012-07-30 00:00:00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
25%,2828.250000,1959.000000,35303.000000,0.000000,0.000000,2013-01-16 00:00:00,24.000000,23.750000,1.000000,16.000000,...,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
50%,5458.500000,1970.000000,51381.500000,0.000000,0.000000,2013-07-08 12:00:00,49.000000,173.500000,8.000000,67.000000,...,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
75%,8427.750000,1977.000000,68522.000000,1.000000,1.000000,2013-12-30 06:00:00,74.000000,504.250000,33.000000,232.000000,...,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
max,11191.000000,1996.000000,666666.000000,2.000000,2.000000,2014-06-29 00:00:00,99.000000,1493.000000,199.000000,1725.000000,...,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.0,11.0,1.000000
std,3246.662198,11.984069,25173.076661,0.538398,0.544538,NaN,28.962453,336.597393,39.773434,225.715373,...,2.426645,0.259813,0.262728,0.259813,0.245316,0.114976,0.096391,0.0,0.0,0.356274

### Step 9-Check data types

In [27]:
data.dtypes

ID                              int64
Year_Birth                      int64
Education                      object
Marital_Status                 object
Income                        float64
Kidhome                         int64
Teenhome                        int64
Dt_Customer            datetime64[ns]
Recency                         int64
MntWines                        int64
MntFruits                       int64
MntMeatProducts                 int64
MntFishProducts                 int64
MntSweetProducts                int64
MntGoldProds                    int64
NumDealsPurchases               int64
NumWebPurchases                 int64
NumCatalogPurchases             int64
NumStorePurchases               int64
NumWebVisitsMonth               int64
AcceptedCmp3                    int64
AcceptedCmp4                    int64
AcceptedCmp5                    int64
AcceptedCmp1                    int64
AcceptedCmp2                    int64
Complain                        int64
Z_CostContact                   int64
Z_Revenue                       int64
Response                        int64
dtype: object

### Step 10 -Check for missing values

In [28]:
data.isnull().sum()

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

### Step 11-Check Duplicate Rows

In [29]:
data.duplicated().sum()

np.int64(0)

Duplicate records can give excessive importance to the same customer and can affect analysis and clustering.

### Step 12- Separate Numercial Columns

In [30]:
num_cols=data.select_dtypes(include=np.number).columns
num_cols

Index(['ID', 'Year_Birth', 'Income', 'Kidhome', 'Teenhome', 'Recency',
       'MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts',
       'MntSweetProducts', 'MntGoldProds', 'NumDealsPurchases',
       'NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases',
       'NumWebVisitsMonth', 'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5',
       'AcceptedCmp1', 'AcceptedCmp2', 'Complain', 'Z_CostContact',
       'Z_Revenue', 'Response'],
      dtype='object')

### Step 13- Separate Categorical Columns

In [31]:
cat_cols=data.select_dtypes(include='object').columns
cat_cols

Index(['Education', 'Marital_Status'], dtype='object')

This is useful because numerical and categorical variables require different types of analysis.

### Step 14- Count Categories

In [32]:
for col in cat_cols:
    print(f"{col}:{data[col].nunique()}unique values")

Education:5unique values
Marital_Status:8unique values

In [33]:
for col in cat_cols:
    print("\n",col)
    print(data[col].value_counts())

 Education
Education
Graduation    1127
PhD            486
Master         370
2n Cycle       203
Basic           54
Name: count, dtype: int64

 Marital_Status
Marital_Status
Married     864
Together    580
Single      480
Divorced    232
Widow        77
Alone         3
Absurd        2
YOLO          2
Name: count, dtype: int64

### Step 15 Histograms

In [34]:
for col in num_cols:
    plt.figure(figsize=(6,3))
    plt.hist(data[col],bins=20,edgecolor='black')
    plt.title(f"Distribution of {col}")
    plt.xlabel(col)
    plt.ylabel("Frequency")
    plt.show()

Histograms shows how values are distribbuted.It helps whether most customers have:low,middle or high income and whether there are unusual extreme values.

### Step 16-Boxplots

In [35]:
for col in num_cols:
    plt.figure(figsize=(6,3))
    plt.boxplot(data[col])
    plt.title(col)
    plt.show()

Boxplots help identify:median, spread,possible outliers

### Step 17-Categorical Visualization

In [36]:
for col in cat_cols:
    plt.figure(figsize=(6,3))
    data[col].value_counts().plot(kind='bar')
    plt.title(f"{col} Distribution")
    plt.xlabel(col)
    plt.ylabel("Count")
    plt.xticks(rotation=45)
    plt.show()

### Step 18 Correlation Matrix

We investigate relationships between numerical variables

In [37]:
plt.figure(figsize=(12,8))
sns.heatmap(
    data.corr(numeric_only=True),
    annot=True,
    cmap='coolwarm'
)
plt.title("Correlation Matrix")
plt.show()

Correlation tells us how  strongly two numerical variables move together.

### Step 19- Look at Correlations Numerically

In [38]:
correlation = data.corr(numeric_only=True)
correlation

,ID,Year_Birth,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
ID,1.000000,0.000028,0.013095,0.002406,-0.002580,-0.046524,-0.022878,0.004600,-0.004437,-0.024475,...,-0.007446,-0.036040,-0.025387,-0.007517,-0.021614,-0.015061,0.033883,NaN,NaN,-0.021968
Year_Birth,0.000028,1.000000,-0.161791,0.230176,-0.352111,-0.019871,-0.157773,-0.017917,-0.030872,-0.041625,...,0.121139,0.061774,-0.060510,0.007123,-0.005930,-0.006539,-0.030128,NaN,NaN,0.021325
Income,0.013095,-0.161791,1.000000,-0.428669,0.019133,-0.003970,0.578650,0.430842,0.584633,0.438871,...,-0.553088,-0.016174,0.184400,0.335943,0.276820,0.087545,-0.027225,NaN,NaN,0.133047
Kidhome,0.002406,0.230176,-0.428669,1.000000,-0.036133,0.008827,-0.496297,-0.372581,-0.437129,-0.387644,...,0.447846,0.014674,-0.161600,-0.205634,-0.172339,-0.081716,0.040207,NaN,NaN,-0.080008
Teenhome,-0.002580,-0.352111,0.019133,-0.036133,1.000000,0.016198,0.004846,-0.176764,-0.261160,-0.204187,...,0.134884,-0.042677,0.038886,-0.191050,-0.140090,-0.015605,0.003138,NaN,NaN,-0.154446
Recency,-0.046524,-0.019871,-0.003970,0.008827,0.016198,1.000000,0.016064,-0.004306,0.023056,0.001079,...,-0.021445,-0.032991,0.018826,0.000129,-0.019283,-0.001781,0.013231,NaN,NaN,-0.198437
MntWines,-0.022878,-0.157773,0.578650,-0.496297,0.004846,0.016064,1.000000,0.389637,0.562667,0.399753,...,-0.320653,0.062202,0.373286,0.472613,0.354133,0.205907,-0.039007,NaN,NaN,0.247254
MntFruits,0.004600,-0.017917,0.430842,-0.372581,-0.176764,-0.004306,0.389637,1.000000,0.543105,0.594804,...,-0.418383,0.014727,0.010152,0.215833,0.194748,-0.009773,-0.005166,NaN,NaN,0.125289
MntMeatProducts,-0.004437,-0.030872,0.584633,-0.437129,-0.261160,0.023056,0.562667,0.543105,1.000000,0.568402,...,-0.539470,0.018272,0.102912,0.373769,0.309761,0.043033,-0.023483,NaN,NaN,0.236335
MntFishProducts,-0.024475,-0.041625,0.438871,-0.387644,-0.204187,0.001079,0.399753,0.594804,0.568402,1.000000,...,-0.446003,0.000357,0.016843,0.199578,0.260762,0.002577,-0.020953,NaN,NaN,0.111331
MntSweetProducts,-0.007642,-0.018133,0.440744,-0.370673,-0.162475,0.022670,0.386581,0.567164,0.523846,0.579870,...,-0.423294,0.001530,0.028641,0.259590,0.241818,0.009985,-0.022485,NaN,NaN,0.117372
MntGoldProds,-0.013438,-0.061818,0.325916,-0.349595,-0.021725,0.016693,0.387516,0.392995,0.350609,0.422875,...,-0.250719,0.123091,0.022268,0.181021,0.166396,0.049990,-0.030861,NaN,NaN,0.139850
NumDealsPurchases,-0.037166,-0.060846,-0.083101,0.221798,0.387741,-0.001098,0.010940,-0.132114,-0.122415,-0.139361,...,0.347633,-0.023109,0.015594,-0.183248,-0.123244,-0.037695,0.000420,NaN,NaN,0.002238
NumWebPurchases,-0.018924,-0.145040,0.387878,-0.361647,0.155500,-0.010726,0.542265,0.296735,0.293761,0.293681,...,-0.055846,0.042176,0.155903,0.138684,0.155143,0.034188,-0.016310,NaN,NaN,0.148730
NumCatalogPurchases,-0.003440,-0.121275,0.589162,-0.502237,-0.110769,0.025110,0.635226,0.487917,0.723827,0.534478,...,-0.520364,0.104730,0.139247,0.322321,0.308097,0.099852,-0.020453,NaN,NaN,0.220810
NumStorePurchases,-0.014927,-0.128272,0.529362,-0.499683,0.050695,0.000799,0.642100,0.461758,0.479659,0.459855,...,-0.428473,-0.067577,0.179379,0.214790,0.183249,0.085189,-0.016524,NaN,NaN,0.039363
NumWebVisitsMonth,-0.007446,0.121139,-0.553088,0.447846,0.134884,-0.021445,-0.320653,-0.418383,-0.539470,-0.446003,...,1.000000,0.061211,-0.032126,-0.278113,-0.192502,-0.007196,0.019769,NaN,NaN,-0.003987
AcceptedCmp3,-0.036040,0.061774,-0.016174,0.014674,-0.042677,-0.032991,0.062202,0.014727,0.018272,0.000357,...,0.061211,1.000000,-0.079512,0.080316,0.094751,0.072020,0.008415,NaN,NaN,0.254258
AcceptedCmp4,-0.025387,-0.060510,0.184400,-0.161600,0.038886,0.018826,0.373286,0.010152,0.102912,0.016843,...,-0.032126,-0.079512,1.000000,0.306526,0.251300,0.292210,-0.027611,NaN,NaN,0.177019
AcceptedCmp5,-0.007517,0.007123,0.335943,-0.205634,-0.191050,0.000129,0.472613,0.215833,0.373769,0.199578,...,-0.278113,0.080316,0.306526,1.000000,0.403078,0.221533,-0.009419,NaN,NaN,0.326634
AcceptedCmp1,-0.021614,-0.005930,0.276820,-0.172339,-0.140090,-0.019283,0.354133,0.194748,0.309761,0.260762,...,-0.192502,0.094751,0.251300,0.403078,1.000000,0.175315,-0.025499,NaN,NaN,0.293982
AcceptedCmp2,-0.015061,-0.006539,0.087545,-0.081716,-0.015605,-0.001781,0.205907,-0.009773,0.043033,0.002577,...,-0.007196,0.072020,0.292210,0.221533,0.175315,1.000000,-0.011334,NaN,NaN,0.169293
Complain,0.033883,-0.030128,-0.027225,0.040207,0.003138,0.013231,-0.039007,-0.005166,-0.023483,-0.020953,...,0.019769,0.008415,-0.027611,-0.009419,-0.025499,-0.011334,1.000000,NaN,NaN,-0.001707
Z_CostContact,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Z_Revenue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Response,-0.021968,0.021325,0.133047,-0.080008,-0.154446,-0.198437,0.247254,0.125289,0.236335,0.111331,...,-0.003987,0.254258,0.177019,0.326634,0.293982,0.169293,-0.001707,NaN,NaN,1.000000

This gives the actual correlation table.
We don't just create the heatmap—we should understand what it means.

### Step 20- Scatter PLot

In [39]:
plt.figure(figsize=(6,4))
plt.scatter(
    data["Income"],
    data["MntWines"]
)
plt.xlabel("Income")
plt.ylabel("Wine Spending")
plt.title("Income Vs Wine Spending")
plt.show()

We are not claiming causation.
We are simply exploring the relationship.

### Step 21-Pairplot

In [40]:
cols=[
    'Income',
    'MntWines',
    'MntMeatProducts',
    'NumWebPurchases',
    'NumStorePurchases'
]
sns.pairplot(data[cols])
plt.show()

A pairplot allows us to visually inspect relationships between multiple variables.

### Step 22- Basic Statistical Measures

In [41]:
data[num_cols].mean()

ID                      5592.159821
Year_Birth              1968.805804
Income                 52247.251354
Kidhome                    0.444196
Teenhome                   0.506250
Recency                   49.109375
MntWines                 303.935714
MntFruits                 26.302232
MntMeatProducts          166.950000
MntFishProducts           37.525446
MntSweetProducts          27.062946
MntGoldProds              44.021875
NumDealsPurchases          2.325000
NumWebPurchases            4.084821
NumCatalogPurchases        2.662054
NumStorePurchases          5.790179
NumWebVisitsMonth          5.316518
AcceptedCmp3               0.072768
AcceptedCmp4               0.074554
AcceptedCmp5               0.072768
AcceptedCmp1               0.064286
AcceptedCmp2               0.013393
Complain                   0.009375
Z_CostContact              3.000000
Z_Revenue                 11.000000
Response                   0.149107
dtype: float64

In [42]:
data[num_cols].median()

ID                      5458.5
Year_Birth              1970.0
Income                 51381.5
Kidhome                    0.0
Teenhome                   0.0
Recency                   49.0
MntWines                 173.5
MntFruits                  8.0
MntMeatProducts           67.0
MntFishProducts           12.0
MntSweetProducts           8.0
MntGoldProds              24.0
NumDealsPurchases          2.0
NumWebPurchases            4.0
NumCatalogPurchases        2.0
NumStorePurchases          5.0
NumWebVisitsMonth          6.0
AcceptedCmp3               0.0
AcceptedCmp4               0.0
AcceptedCmp5               0.0
AcceptedCmp1               0.0
AcceptedCmp2               0.0
Complain                   0.0
Z_CostContact              3.0
Z_Revenue                 11.0
Response                   0.0
dtype: float64

In [43]:
data[num_cols].std()

ID                      3246.662198
Year_Birth                11.984069
Income                 25173.076661
Kidhome                    0.538398
Teenhome                   0.544538
Recency                   28.962453
MntWines                 336.597393
MntFruits                 39.773434
MntMeatProducts          225.715373
MntFishProducts           54.628979
MntSweetProducts          41.280498
MntGoldProds              52.167439
NumDealsPurchases          1.932238
NumWebPurchases            2.778714
NumCatalogPurchases        2.923101
NumStorePurchases          3.250958
NumWebVisitsMonth          2.426645
AcceptedCmp3               0.259813
AcceptedCmp4               0.262728
AcceptedCmp5               0.259813
AcceptedCmp1               0.245316
AcceptedCmp2               0.114976
Complain                   0.096391
Z_CostContact              0.000000
Z_Revenue                  0.000000
Response                   0.356274
dtype: float64

These give us the central tendency and spread of numerical variables.

### Step 23-IQR

In [44]:
Q1=data[num_cols].quantile(0.25)
Q3=data[num_cols].quantile(0.75)
IQR=Q3-Q1
IQR

ID                      5599.5
Year_Birth                18.0
Income                 33219.0
Kidhome                    1.0
Teenhome                   1.0
Recency                   50.0
MntWines                 480.5
MntFruits                 32.0
MntMeatProducts          216.0
MntFishProducts           47.0
MntSweetProducts          32.0
MntGoldProds              47.0
NumDealsPurchases          2.0
NumWebPurchases            4.0
NumCatalogPurchases        4.0
NumStorePurchases          5.0
NumWebVisitsMonth          4.0
AcceptedCmp3               0.0
AcceptedCmp4               0.0
AcceptedCmp5               0.0
AcceptedCmp1               0.0
AcceptedCmp2               0.0
Complain                   0.0
Z_CostContact              0.0
Z_Revenue                  0.0
Response                   0.0
dtype: float64

It represents the middle 50% of the data.
It is useful for identifying potential outliers.

### Step 24-Check Suspious Values

In [45]:
data[data['Year_Birth']<1900]

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
239,11004,1893,2n Cycle,Single,60182.0,0,1,2014-05-17,23,8,...,4,0,0,0,0,0,0,3,11,0
339,1150,1899,PhD,Together,83532.0,0,0,2013-09-26,36,755,...,1,0,0,1,0,0,0,3,11,0

### Step 25-Investigate Extremely High Income

In [46]:
data[data['Income']>200000]

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
2233,9432,1977,Graduation,Together,666666.0,1,0,2013-06-02,23,9,...,6,0,0,0,0,0,0,3,11,0

### Step 25-Check Response Distribution

In [47]:
data['Response'].value_counts()

Response
0    1906
1     334
Name: count, dtype: int64

In [48]:
plt.figure(figsize=(5,4))
data['Response'].value_counts().plot(kind='bar')
plt.title("Customer Response Distribution")
plt.xlabel("Response")
plt.ylabel("Number of Customers")
plt.show()

### Step 27-Check Campaign Acceptance

In [49]:
campaign_cols=[
    'AcceptedCmp1',
    'AcceptedCmp2',
    'AcceptedCmp3',
    'AcceptedCmp4',
    'AcceptedCmp5',
]
data[campaign_cols].sum()

AcceptedCmp1    144
AcceptedCmp2     30
AcceptedCmp3    163
AcceptedCmp4    167
AcceptedCmp5    163
dtype: int64

In [50]:
print("Final Dataset Shape:", data.shape)
print("\nFinal Dataset Columns:")
print(data.columns.tolist())

print("\nFinal Dataset Information:")
data.info()

print("\nFirst 5 Rows:")
display(data.head())

Final Dataset Shape: (2240, 29)

Final Dataset Columns:
['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts', 'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth', 'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1', 'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response']

Final Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   datetime64[ns]
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(25), object(2)
memory usage: 507.6+ KB

First 5 Rows:

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,...,5,0,0,0,0,0,0,3,11,0

This tells us how many customers accepted each campaign.

#### Customer Enrollment Date Analysis
The Dt_Customer column records when each customer enrolled with the company.
This analysis examines the monthly enrollment pattern in the available dataset.

### Check the dates

In [51]:
data['Dt_Customer'] = pd.to_datetime(
    data['Dt_Customer'],
    errors='coerce'
)

print("Earliest enrollment date:")
print(data['Dt_Customer'].min())

print("\nLatest enrollment date:")
print(data['Dt_Customer'].max())

print("\nMissing enrollment dates:")
print(data['Dt_Customer'].isnull().sum())

Earliest enrollment date:
2012-07-30 00:00:00

Latest enrollment date:
2014-06-29 00:00:00

Missing enrollment dates:
0

### Monthly enrollment trend

In [52]:
date_data = data.dropna(subset=['Dt_Customer']).copy()

monthly_customers = (
    date_data
    .set_index('Dt_Customer')
    .resample('MS')
    .size()
)

plt.figure(figsize=(10, 5))

plt.plot(
    monthly_customers.index,
    monthly_customers.values,
    marker='o'
)

plt.xlabel("Enrollment Month")
plt.ylabel("Number of Customers")
plt.title("Monthly Customer Enrollment Trend")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

##### Observation: The monthly enrollment chart shows how customer registrations are distributed across the recorded months. The months with the highest and lowest enrollment should be identified from the actual chart.
Limitation: This dataset records customer enrollment dates and summary-level purchasing behaviour. It does not contain a complete monthly transaction history, so the chart should not be interpreted as a monthly sales trend.

### Week 2

### Step1:Import Libraries for modelling

In [53]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.mixture import GaussianMixture

from sklearn.metrics import (
    silhouette_score,
    davies_bouldin_score,
    calinski_harabasz_score
)

These are the libraries needed for preprocessing, clustering, dimensionality reduction, and evaluating cluster quality using multiple metrics.

### Step 2 — Create a copy of your EDA dataset

In [54]:
model_data = data.copy()
model_data.shape

(2240, 29)

A separate copy of the dataset is created so that preprocessing and model-related changes do not affect the original dataset used during EDA.

### Step 3 — Handle Missing Values

In [55]:
model_data['Income'] = model_data['Income'].fillna(
    model_data['Income'].median()
)
model_data.isnull().sum().sum()

np.int64(0)

Missing Income values are replaced with the median Income.
Median is used because it is less affected by extreme values than the mean.

### Step 4 — Feature Engineering

In [56]:
# Total spending by customer
model_data['Total_Spend'] = (
    model_data['MntWines'] +
    model_data['MntFruits'] +
    model_data['MntMeatProducts'] +
    model_data['MntFishProducts'] +
    model_data['MntSweetProducts'] +
    model_data['MntGoldProds']
)

# Total purchases through different channels
model_data['Total_Purchases'] = (
    model_data['NumWebPurchases'] +
    model_data['NumCatalogPurchases'] +
    model_data['NumStorePurchases']
)

# Total children and teenagers
model_data['Total_Children'] = (
    model_data['Kidhome'] +
    model_data['Teenhome']
)

# Total accepted campaigns
model_data['Total_Campaign_Accepted'] = (
    model_data['AcceptedCmp1'] +
    model_data['AcceptedCmp2'] +
    model_data['AcceptedCmp3'] +
    model_data['AcceptedCmp4'] +
    model_data['AcceptedCmp5']
)


These features combine related variables into simple measures of customer behaviour.
They help the clustering models identify customers with similar spending, purchasing and promotional behaviour.
New features are created to summarize important aspects of customer behaviour such as total spending, total purchases, family size and campaign acceptance.

### Calculate customer tenure in days

In [57]:
model_data['Dt_Customer'] = pd.to_datetime(
    model_data['Dt_Customer'],
    errors='coerce'
)

reference_date = model_data['Dt_Customer'].max()

model_data['Customer_Tenure_Days'] = (
    reference_date - model_data['Dt_Customer']
).dt.days

print("Customer tenure created successfully.")

print(
    model_data['Customer_Tenure_Days']
    .describe()
)

Customer tenure created successfully.
count    2240.000000
mean      353.582143
std       202.122512
min         0.000000
25%       180.750000
50%       355.500000
75%       529.000000
max       699.000000
Name: Customer_Tenure_Days, dtype: float64

This measures how long each customer had been enrolled relative to the latest enrollment date in the dataset. It is a relative tenure measure, not necessarily the customer's true tenure at the original data snapshot date.

### Step5 — Select features

In [58]:
features = [
    'Income',
    'Recency',
    'Total_Spend',
    'Total_Purchases',
    'NumDealsPurchases',
    'NumWebVisitsMonth',
    'Total_Children',
    'Total_Campaign_Accepted',
    'NumWebPurchases',
    'NumCatalogPurchases',
    'NumStorePurchases',
    'Customer_Tenure_Days'
]

X = model_data[features]

X.head()

,Income,Recency,Total_Spend,Total_Purchases,NumDealsPurchases,NumWebVisitsMonth,Total_Children,Total_Campaign_Accepted,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,Customer_Tenure_Days
0,58138.0,58,1617,22,3,7,0,0,8,10,4,663
1,46344.0,38,27,4,2,5,2,0,1,1,2,113
2,71613.0,26,776,20,1,4,0,0,8,2,10,312
3,26646.0,26,53,6,2,6,1,0,2,0,4,139
4,58293.0,94,422,14,5,5,1,0,5,3,6,161

Relevant numerical variables are selected for clustering.
Identifier and non-behavioural variables are excluded because they do not provide useful information for forming customer segments.The selected features represent customer income, recency, spending, purchasing behaviour, family information and campaign participation.
These variables will be used as inputs to the clustering models.

### Step 6 — Check the modelling data

In [59]:
print("Shape of modelling data:", X.shape)
print("\nMissing values:")
print(X.isnull().sum())

Shape of modelling data: (2240, 12)

Missing values:
Income                     0
Recency                    0
Total_Spend                0
Total_Purchases            0
NumDealsPurchases          0
NumWebVisitsMonth          0
Total_Children             0
Total_Campaign_Accepted    0
NumWebPurchases            0
NumCatalogPurchases        0
NumStorePurchases          0
Customer_Tenure_Days       0
dtype: int64

The selected dataset is checked once again to make sure that the variables used for modelling are numerical and contain no missing values.

### Step 7 — Standardize the features

In [60]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled = pd.DataFrame(
    X_scaled,
    columns=X.columns,
    index=X.index
)
X_scaled.head()

,Income,Recency,Total_Spend,Total_Purchases,NumDealsPurchases,NumWebVisitsMonth,Total_Children,Total_Campaign_Accepted,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,Customer_Tenure_Days
0,0.235696,0.307039,1.679417,1.313544,0.349414,0.693904,-1.264505,-0.439037,1.409304,2.510890,-0.550785,1.531185
1,-0.235454,-0.383664,-0.961275,-1.185022,-0.168236,-0.130463,1.396361,-0.439037,-1.110409,-0.568720,-1.166125,-1.190545
2,0.773999,-0.798086,0.282673,1.035926,-0.685887,-0.542647,-1.264505,-0.439037,1.409304,-0.226541,1.295237,-0.205773
3,-1.022355,-0.798086,-0.918094,-0.907403,-0.168236,0.281720,0.065928,-0.439037,-0.750450,-0.910898,-0.550785,-1.061881
4,0.241888,1.550305,-0.305254,0.203070,1.384715,-0.130463,0.065928,-0.439037,0.329427,0.115638,0.064556,-0.953012

StandardScaler transforms the features so that they have a similar scale.
This prevents variables with larger numerical values from dominating the clustering process.

### Step 8 — K-MEANS: Find suitable K

In [61]:
from sklearn.cluster import KMeans
wcss = []
for k in range(2, 11):
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)

In [62]:
plt.figure(figsize=(8, 5))

plt.plot(
    range(2, 11),
    wcss,
    marker='o'
)

plt.xlabel("Number of Clusters (K)")
plt.ylabel("WCSS")
plt.title("Elbow Method")

plt.show()

The Elbow Method shows how within-cluster variation changes as the number of clusters increases.
The point where the improvement starts becoming smaller can be considered as a possible number of clusters.

### Step 9 — Silhouette Score for K

In [63]:
from sklearn.metrics import silhouette_score
silhouette_scores = []
for k in range(2, 11):
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )
    labels = kmeans.fit_predict(X_scaled)
    
    score = silhouette_score(
        X_scaled,
        labels
    )
    silhouette_scores.append(score)
for k, score in zip(range(2, 11), silhouette_scores):
    print(f"K = {k} : Silhouette Score = {score:.4f}")

K = 2 : Silhouette Score = 0.3103
K = 3 : Silhouette Score = 0.2510
K = 4 : Silhouette Score = 0.2426
K = 5 : Silhouette Score = 0.2220
K = 6 : Silhouette Score = 0.1569
K = 7 : Silhouette Score = 0.1576
K = 8 : Silhouette Score = 0.1471
K = 9 : Silhouette Score = 0.1418
K = 10 : Silhouette Score = 0.1409

In [64]:
plt.figure(figsize=(8, 5))

plt.plot(
    range(2, 11),
    silhouette_scores,
    marker='o'
)

plt.xlabel("Number of Clusters")
plt.ylabel("Silhouette Score")
plt.title("Silhouette Score for Different K Values")

plt.show()

The Silhouette Score measures how well each customer fits within its assigned cluster compared with other clusters.
A higher score generally indicates better separation between clusters.

### Step 10 — Build K-Means

In [65]:
k = 5

kmeans = KMeans(
    n_clusters=k,
    random_state=42,
    n_init=10
)

kmeans_labels = kmeans.fit_predict(X_scaled)

model_data['KMeans_Cluster'] = kmeans_labels

model_data['KMeans_Cluster'].value_counts().sort_index()

KMeans_Cluster
0    304
1    975
2    394
3    441
4    126
Name: count, dtype: int64

K-Means assigns each customer to one of five clusters based on similarity in the selected features.
Each cluster represents a potential customer segment.

### Step 11 — Evaluate K-Means

In [66]:
from sklearn.metrics import (
    silhouette_score,
    davies_bouldin_score,
    calinski_harabasz_score
)

kmeans_silhouette = silhouette_score(
    X_scaled,
    kmeans_labels
)

kmeans_db = davies_bouldin_score(
    X_scaled,
    kmeans_labels
)

kmeans_ch = calinski_harabasz_score(
    X_scaled,
    kmeans_labels
)

print("K-Means Evaluation")
print("------------------")
print("Silhouette Score:", round(kmeans_silhouette, 4))
print("Davies-Bouldin Index:", round(kmeans_db, 4))
print("Calinski-Harabasz Score:", round(kmeans_ch, 4))

K-Means Evaluation
------------------
Silhouette Score: 0.222
Davies-Bouldin Index: 1.7683
Calinski-Harabasz Score: 539.9943

The K-Means model is evaluated using three internal clustering metrics.
Higher Silhouette and Calinski-Harabasz scores are preferred, while a lower Davies-Bouldin score is preferred.

### Step  12 — MODEL 2: HIERARCHICAL CLUSTERING

In [67]:
from sklearn.cluster import AgglomerativeClustering

hierarchical = AgglomerativeClustering(
    n_clusters=5,
    linkage='ward'
)

hierarchical_labels = hierarchical.fit_predict(X_scaled)

model_data['Hierarchical_Cluster'] = hierarchical_labels

model_data['Hierarchical_Cluster'].value_counts().sort_index()

Hierarchical_Cluster
0    947
1    162
2    334
3    419
4    378
Name: count, dtype: int64

The hierarchical model groups customers based on their similarity and creates five customer segments.
The resulting cluster assignments will be evaluated using the same metrics as K-Means.

### Step 12 — Evaluate Hierarchical

In [68]:
hier_silhouette = silhouette_score(
    X_scaled,
    hierarchical_labels
)

hier_db = davies_bouldin_score(
    X_scaled,
    hierarchical_labels
)

hier_ch = calinski_harabasz_score(
    X_scaled,
    hierarchical_labels
)

print("Hierarchical Clustering Evaluation")
print("----------------------------------")
print("Silhouette Score:", round(hier_silhouette, 4))
print("Davies-Bouldin Index:", round(hier_db, 4))
print("Calinski-Harabasz Score:", round(hier_ch, 4))

Hierarchical Clustering Evaluation
----------------------------------
Silhouette Score: 0.1895
Davies-Bouldin Index: 2.0067
Calinski-Harabasz Score: 490.7957

The hierarchical clustering results are evaluated using Silhouette Score, Davies-Bouldin Index and Calinski-Harabasz Score.
These results will later be compared with the other clustering models.

### Step 13 — Dendrogram

In [69]:
from scipy.cluster.hierarchy import dendrogram, linkage

linkage_matrix = linkage(
    X_scaled,
    method='ward'
)

plt.figure(figsize=(12, 6))

dendrogram(
    linkage_matrix,
    truncate_mode='lastp',
    p=30
)

plt.title("Hierarchical Clustering Dendrogram")
plt.xlabel("Customers / Groups")
plt.ylabel("Distance")

plt.show()

The dendrogram shows how observations are progressively combined into groups.
It provides a visual representation of the hierarchical structure of the customer data.

### Step 14 — MODEL 3: DBSCAN

In [70]:
from sklearn.cluster import DBSCAN

dbscan = DBSCAN(
    eps=0.8,
    min_samples=5
)

dbscan_labels = dbscan.fit_predict(X_scaled)

model_data['DBSCAN_Cluster'] = dbscan_labels

model_data['DBSCAN_Cluster'].value_counts().sort_index()

DBSCAN_Cluster
-1     1797
 0      308
 1        5
 2       16
 3        8
 4       49
 5        5
 6        5
 7       10
 8        5
 9        7
 10       5
 11       5
 12       5
 13       5
 14       5
Name: count, dtype: int64

DBSCAN groups customers based on the density of nearby observations.
Customers that do not belong to a sufficiently dense region are identified as noise.

### Step 15 — Evaluate DBSCAN

In [71]:
mask = dbscan_labels != -1

n_clusters_dbscan = len(
    set(dbscan_labels)
) - (1 if -1 in dbscan_labels else 0)

print("Number of clusters:", n_clusters_dbscan)
print("Number of noise points:", (~mask).sum())

Number of clusters: 15
Number of noise points: 1797

In [72]:
if n_clusters_dbscan >= 2:
    
    dbscan_silhouette = silhouette_score(
        X_scaled[mask],
        dbscan_labels[mask]
    )
    
    dbscan_db = davies_bouldin_score(
        X_scaled[mask],
        dbscan_labels[mask]
    )
    
    dbscan_ch = calinski_harabasz_score(
        X_scaled[mask],
        dbscan_labels[mask]
    )
    
    print("Silhouette Score:", round(dbscan_silhouette, 4))
    print("Davies-Bouldin Index:", round(dbscan_db, 4))
    print("Calinski-Harabasz Score:", round(dbscan_ch, 4))
    
else:
    print("DBSCAN did not produce enough clusters for evaluation.")

Silhouette Score: -0.0263
Davies-Bouldin Index: 1.0384
Calinski-Harabasz Score: 22.501

The GMM model is evaluated using the same clustering metrics used for the other models.
Using common metrics allows the four models to be compared fairly.

In [73]:
from sklearn.mixture import GaussianMixture

gmm = GaussianMixture(
    n_components=5,
    random_state=42
)

gmm_labels = gmm.fit_predict(X_scaled)

model_data['GMM_Cluster'] = gmm_labels

model_data['GMM_Cluster'].value_counts().sort_index()

GMM_Cluster
0    1152
1     484
2     207
3     396
4       1
Name: count, dtype: int64

In [74]:
gmm_silhouette = silhouette_score(
    X_scaled,
    gmm_labels
)

gmm_db = davies_bouldin_score(
    X_scaled,
    gmm_labels
)

gmm_ch = calinski_harabasz_score(
    X_scaled,
    gmm_labels
)

print("GMM Evaluation")
print("----------------")
print("Silhouette Score:", round(gmm_silhouette, 4))
print("Davies-Bouldin Index:", round(gmm_db, 4))
print("Calinski-Harabasz Score:", round(gmm_ch, 4))

GMM Evaluation
----------------
Silhouette Score: 0.1904
Davies-Bouldin Index: 2.5306
Calinski-Harabasz Score: 323.9821

### Step 19 - Compare ALL FOUR MODELS

In [75]:
results = pd.DataFrame({
    'Model': [
        'K-Means',
        'Hierarchical',
        'DBSCAN',
        'GMM'
    ],
    'Silhouette Score': [
        kmeans_silhouette,
        hier_silhouette,
        dbscan_silhouette,
        gmm_silhouette
    ],
    'Davies-Bouldin Index': [
        kmeans_db,
        hier_db,
        dbscan_db,
        gmm_db
    ],
    'Calinski-Harabasz Score': [
        kmeans_ch,
        hier_ch,
        dbscan_ch,
        gmm_ch
    ]
})

results = results.round(4)

results

,Model,Silhouette Score,Davies-Bouldin Index,Calinski-Harabasz Score
0,K-Means,0.2220,1.7683,539.9943
1,Hierarchical,0.1895,2.0067,490.7957
2,DBSCAN,-0.0263,1.0384,22.5010
3,GMM,0.1904,2.5306,323.9821

The four clustering algorithms are compared using common evaluation metrics.
This comparison helps identify the model that provides a suitable balance between cluster quality and practical customer segmentation.

### Step 20 — Sort the models

In [76]:
ranked_results = results.sort_values(
    by='Silhouette Score',
    ascending=False,
    na_position='last'
)

ranked_results

,Model,Silhouette Score,Davies-Bouldin Index,Calinski-Harabasz Score
0,K-Means,0.2220,1.7683,539.9943
3,GMM,0.1904,2.5306,323.9821
1,Hierarchical,0.1895,2.0067,490.7957
2,DBSCAN,-0.0263,1.0384,22.5010

The models are ranked according to their Silhouette Score.
However, the final model is not selected using one metric alone; Davies-Bouldin Index, Calinski-Harabasz Score and cluster distribution are also considered.

### Step 21 — Compare cluster sizes

In [77]:
print("K-Means")
print(model_data['KMeans_Cluster'].value_counts().sort_index())

print("\nHierarchical")
print(model_data['Hierarchical_Cluster'].value_counts().sort_index())

print("\nDBSCAN")
print(model_data['DBSCAN_Cluster'].value_counts().sort_index())

print("\nGMM")
print(model_data['GMM_Cluster'].value_counts().sort_index())

K-Means
KMeans_Cluster
0    304
1    975
2    394
3    441
4    126
Name: count, dtype: int64

Hierarchical
Hierarchical_Cluster
0    947
1    162
2    334
3    419
4    378
Name: count, dtype: int64

DBSCAN
DBSCAN_Cluster
-1     1797
 0      308
 1        5
 2       16
 3        8
 4       49
 5        5
 6        5
 7       10
 8        5
 9        7
 10       5
 11       5
 12       5
 13       5
 14       5
Name: count, dtype: int64

GMM
GMM_Cluster
0    1152
1     484
2     207
3     396
4       1
Name: count, dtype: int64

### Step 22 — Choose the final model

The four clustering models are compared using Silhouette Score, Davies-Bouldin Index, Calinski-Harabasz Score and cluster size distribution.

The final model will be selected based on both numerical evaluation and the practical interpretability of the resulting customer segments.

Based on the comparison, K-Means provides a suitable balance between clustering performance and business interpretability.
Therefore, K-Means is selected as the final model for customer segmentation.

Based on the comparison, GMM provides better clustering performance and meaningful customer segments.
Therefore, GMM is selected as the final model for customer segmentation.

### Step 23 — Customer Segment Profiling

In [78]:
profile_features = [
    'Income',
    'Recency',
    'Total_Spend',
    'Total_Purchases',
    'NumDealsPurchases',
    'NumWebVisitsMonth',
    'Total_Children',
    'Total_Campaign_Accepted',
    'Customer_Tenure_Days'
]

cluster_profile = model_data.groupby(
    'KMeans_Cluster'
)[profile_features].mean().round(2)

cluster_profile

,Income,Recency,Total_Spend,Total_Purchases,NumDealsPurchases,NumWebVisitsMonth,Total_Children,Total_Campaign_Accepted,Customer_Tenure_Days
KMeans_Cluster,,,,,,,,,
0,47843.45,49.27,462.82,13.02,5.53,7.15,1.57,0.22,463.48
1,35019.30,49.13,90.94,5.65,1.78,6.29,1.19,0.08,306.31
2,75562.92,51.76,1289.55,18.60,1.16,2.14,0.13,0.29,311.64
3,62908.60,46.59,950.39,19.95,2.68,5.29,0.92,0.21,419.10
4,85796.50,49.10,1590.63,19.82,1.18,3.44,0.27,2.51,356.06

This assumes K-Means remains your final model. If your evaluation shows that another algorithm is more suitable, use that model's label column instead.

### Step 24— Number of customers in each segment

In [79]:
cluster_counts = (
    model_data['KMeans_Cluster']
    .value_counts()
    .sort_index()
)

cluster_counts

KMeans_Cluster
0    304
1    975
2    394
3    441
4    126
Name: count, dtype: int64

The number of customers in each cluster is calculated to understand the size of every customer segment.
This is useful when deciding which segments should receive greater marketing attention.

### Step 25 — Percentage of customers

In [80]:
cluster_percentage = (
    model_data['KMeans_Cluster']
    .value_counts(normalize=True)
    .sort_index() * 100
)
cluster_percentage.round(2)

KMeans_Cluster
0    13.57
1    43.53
2    17.59
3    19.69
4     5.62
Name: proportion, dtype: float64

### Step 26 — Visualize customer segments

In [81]:
plt.figure(figsize=(8, 6))

plt.scatter(
    model_data['Income'],
    model_data['Total_Spend'],
    c=model_data['KMeans_Cluster'],
    alpha=0.6
)

plt.xlabel("Income")
plt.ylabel("Total Spend")
plt.title("Customer Segments - Income vs Total Spend")

plt.show()

The scatter plot provides a visual representation of the identified customer segments using Income and Total Spending.
It helps us observe how customers with different income and spending patterns are distributed.

### Step 27 — Cluster profile heatmap

In [82]:
profile_scaled = pd.DataFrame(
    StandardScaler().fit_transform(cluster_profile),
    columns=cluster_profile.columns,
    index=cluster_profile.index
)
plt.figure(figsize=(12, 6))
sns.heatmap(
    profile_scaled,
    annot=True,
    fmt=".2f",
    cmap="coolwarm"
)
plt.title("Customer Segment Profile")
plt.xlabel("Features")
plt.ylabel("Cluster")
plt.show()

A heatmap is used to compare the average characteristics of the identified customer segments.
This makes it easier to identify high-value, low-value, frequent or less-active customer groups.

### Step 28 — Final business interpretation

The four clustering algorithms were evaluated using Silhouette Score, Davies–Bouldin Index and Calinski–Harabasz Score. Cluster sizes and business interpretability were also considered. Based on the observed evaluation results, K-Means was selected as the final model because it provided a suitable balance between cluster quality and practical interpretation of customer segments.

In [83]:
print("Model:", kmeans)
print("Number of clusters:", kmeans.n_clusters)
print("Number of features:", len(X.columns))
print("Feature names:", list(X.columns))
print("Scaler feature count:", scaler.n_features_in_)
print("Reference date:", reference_date)

Model: KMeans(n_clusters=5, n_init=10, random_state=42)
Number of clusters: 5
Number of features: 12
Feature names: ['Income', 'Recency', 'Total_Spend', 'Total_Purchases', 'NumDealsPurchases', 'NumWebVisitsMonth', 'Total_Children', 'Total_Campaign_Accepted', 'NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases', 'Customer_Tenure_Days']
Scaler feature count: 12
Reference date: 2014-06-29 00:00:00

### Week 3

In [88]:
import os
import pickle
import pandas as pd

# Create folder
os.makedirs("deployment", exist_ok=True)

# 1. Save K-Means model
with open("deployment/kmeans_model.pkl", "wb") as f:
    pickle.dump(kmeans, f)

# 2. Save scaler
with open("deployment/scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

# 3. Save feature names
with open("deployment/feature_columns.pkl", "wb") as f:
    pickle.dump(list(X.columns), f)

# 4. Create and save cluster profile CSV
profile_data = X.copy()
profile_data["KMeans_Cluster"] = kmeans.labels_

cluster_profiles = profile_data.groupby("KMeans_Cluster").mean()
cluster_profiles.to_csv("deployment/cluster_profiles.csv")

print("All files created successfully!")
print(os.listdir("deployment"))

All files created successfully!
['cluster_profiles.csv', 'feature_columns.pkl', 'kmeans_model.pkl', 'scaler.pkl']

In [89]:
import os
import pickle

folder = "deployment"

for filename in [
    "kmeans_model.pkl",
    "scaler.pkl",
    "feature_columns.pkl"
]:
    path = os.path.join(folder, filename)

    with open(path, "rb") as f:
        obj = pickle.load(f)

    print(filename, "loaded successfully")

print("CSV exists:", os.path.exists(
    os.path.join(folder, "cluster_profiles.csv")
))

kmeans_model.pkl loaded successfully
scaler.pkl loaded successfully
feature_columns.pkl loaded successfully
CSV exists: True